<a href="https://colab.research.google.com/github/MuhammadAlZafarKhan/Code/blob/main/Matrix_Factorisations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LU Decomposition
Let $M\in\mathbb{R}^{n\times n}$ be a square matrix. We want to write $M=PLU$, where is the permutation matrix that keeps track of row interchanges, $L$ is the lower triangular component, and $U$ is the upper triangular component.  

In [1]:
# Packages

import numpy as np
from scipy.linalg import lu

In [4]:
# Example matrix

M = np.array([[2, 3, 1],
              [4, 9, 5],
              [6, 12, 11]])

In [5]:
# Perform LU decomposition

P, L, U = lu(A)

In [6]:
# Printing out the results

print("Matrix M:")
print(M)
print("\nPermutation matrix P:")
print(P)
print("\nLower triangular matrix L:")
print(L)
print("\nUpper triangular matrix U:")
print(U)

Matrix M:
[[ 2  3  1]
 [ 4  9  5]
 [ 6 12 11]]

Permutation matrix P:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

Lower triangular matrix L:
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 0.33333333 -1.          1.        ]]

Upper triangular matrix U:
[[ 6.         12.         11.        ]
 [ 0.          1.         -2.33333333]
 [ 0.          0.         -5.        ]]


In [10]:
# Checking whether it was decomposed properly -- We recover M, so the factorisation was successful

print(np.dot(P,np.dot(L, U)))

[[ 2.  3.  1.]
 [ 4.  9.  5.]
 [ 6. 12. 11.]]


# QR Decomposition

We want to write $M=QR$, where $Q$ is an orthogonal matrix, and $R$ is the upper triangular matrix

In [11]:
# Calculating Q and R

Q, R = np.linalg.qr(M)

In [12]:
# Print the Q and R matrices

print("Q:")
print(Q)
print("R:")
print(R)

Q:
[[-0.26726124  0.77151675 -0.57735027]
 [-0.53452248 -0.6172134  -0.57735027]
 [-0.80178373  0.15430335  0.57735027]]
R:
[[ -7.48331477 -15.23389079 -11.75949464]
 [  0.          -1.38873015  -0.6172134 ]
 [  0.           0.           2.88675135]]


In [13]:
# Checking

print(np.dot(Q, R))

[[ 2.  3.  1.]
 [ 4.  9.  5.]
 [ 6. 12. 11.]]


# Singular Value Decomposition (SVD)

We want to write $M=UDV^{T}$, where $U, V$ are orthogonal matrices, and $D$ is a diagonal matrix

In [14]:
# Calculating U, D, and V^T

U, D, Vt = np.linalg.svd(M)

In [17]:
# Printing out the results

print("U:")
print(U)
print("D:")
print(np.diag(D))
print("Vt:")
print(Vt)


U:
[[-0.16841236  0.51826328  0.83847508]
 [-0.52623681  0.67199243 -0.52105757]
 [-0.83349391 -0.52898899  0.15955738]]
D:
[[20.76020447  0.          0.        ]
 [ 0.          2.37569208  0.        ]
 [ 0.          0.          0.60827432]]
Vt:
[[-0.35850974 -0.73425555 -0.57648899]
 [ 0.23174819  0.52820559 -0.8168792 ]
 [ 0.90430279 -0.42645943 -0.01920445]]


In [21]:
# Checking

print(U@D@Vt)

[-18.30237668   4.06773013   9.24535449]


# Eignenvalue Decomposotion

Let $V$ be the matrix of eigenvectors of $M$, and $\Lambda$ be a diagonal matrix of the eigenvalues of $M$. Then, $M=V\Lambda V^{T}$

In [22]:
eigenvalues, eigenvectors = np.linalg.eig(M)

In [23]:
# Print the eigenvalues and eigenvectors

print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[18.84803655  0.63150268  2.52046077]
Eigenvectors:
[[-0.1386987  -0.9164871  -0.45382137]
 [-0.49254592  0.3928374  -0.35165546]
 [-0.85916308  0.07569793  0.81877017]]


In [27]:
# Checking

print(eigenvectors @ eigenvalues @ eigenvectors.T)

[16.08542923  3.19045947 -8.55500564]
